### ISSUE TITLE
Improve output in the terminal

### ISSUE THREAD

**Issue by Gonmeso** [gizatechxyz/giza-cli#15]
Currently we have different methods of showing the outputs of our current resources, some of the are just printing the `json` received requested to the API in others we just print out the logs.

When we are dealing with getting information about a specific resource we are just printing the json, for this we could make the output in two ways:

* By default use a Rich `Table` to output the requested resources so it easy to get the information
* Add a `--json` option to output the requested resources as a json as we were doing now

For commands that we are performing multiple actions with one or more resources if the `--debug` option is provided we could add this table output for better debugging the API calls.

**Comment by jbmkahdeksan** [comment]
hello!
I am interested in contributing with this issue
could you please assign it to me?

**Comment by Gonmeso** [comment]
Hi @jbmkahdeksan feel free to take it!

To give a little more input on this the output by default should be a rich table: https://rich.readthedocs.io/en/stable/tables.html

<img width="699" alt="image" src="https://github.com/gizatechxyz/giza-cli/assets/18899187/adc8c19a-0167-41c3-b08f-f5217676b85c">

This output will print all the logs and then the table.

And then anything that receives a json output like creating, listing or getting should have a `typer.Option(..., "--json")`. This mode will not print the output but save it into a file `giza.log` (creating a new one if it exists). If the execution fails, this file is printed.

For example `giza models list`:

`default behaviour`
```console
> giza models list
[giza][2023-09-13 13:11:39.403] Listing models ✅ 
```
| ID  | Name | description |
| ------------- | ------------- | ------------- |
| 1  | my_new_model  | A New Model |
| 2  | Test  | A Model for testing different models |

`--json behaviour`
```console
> giza models list --json
[
  {
    "id": 1,
    "name": "my_new_model",
    "description": "A New Model"
  },
  {
    "id": 2,
    "name": "Test",
    "description": "A Model for testing different models"
  }
]
```

Here, logs are not printed but saved into `giza.log`

As the final test of this, `jq` should be able to work with it, for example to access the data of the second model:

```console
giza models list --json | jq '.[1] | {name, description}'
{
  "name": "Test",
  "description": "A Model for testing different models"
}
```

**Comment by jbmkahdeksan** [comment]
Ok @Gonmeso
So is this for all commands that print outputs?

**Comment by Gonmeso** [comment]
Yes @jbmkahdeksan I was thinking about a function that takes a pydantic model as and input and prints the table or returns the json.

```python
def model_info_handler(model: Union[BaseModel, RootModel], json: bool = json_option):
    # If json we return the data
    if json:
        return model.model_dump()
    # 1. Extract model fields and handle `RootModel`
    ...
    # 2. Create table columns
    ...
    # 3. Fill rows
    ...
    # 4. Print table
    ...
```

**Comment by Gonmeso** [comment]
Hi @jbmkahdeksan 

This issue has been prioritised from our side, I understand that you might have done some work on it, but we need to hurry on this.

If you dont feel confortable I can take it, as we have prioritised this as we want to use it for CI and to improve the UX in the tutorials.

**Comment by jbmkahdeksan** [comment]
Hello @Gonmeso 
I understand  and don't want to jeopardize your line of work. I have done some work, but haven't treat this as a priority. Go ahead and do what you got to do!
Thanks for the opportunity, though
Hope we could find another opportunity to keep contributing to Giza! :)
