### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by traderalexfly** [gizatechxyz/giza-cli#23]
pip install giza-cli return 
Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.11,<4.0; 0.0.2 Requires-Python >=3.11,<4.0; 0.2.0 Requires-Python >=3.11,<4.0; 0.2.1 Requires-Python >=3.11,<4.0; 0.3.0 Requires-Python >=3.11,<4.0; 0.4.0 Requires-Python >=3.11,<4.0
ERROR: Could not find a version that satisfies the requirement giza-cli (from versions: none)
ERROR: No matching distribution found for giza-cli

expect：
The required python version is stated in the documentation.

**Comment by Gonmeso** [comment]
Hello @traderalexfly 

Thank you for opening this issue, as the error states we are using python 3.11 and onwards but we have not commented so in the docs.

We will add this to the docs and include a short tutorial on using `pyenv` for handling different python versions in the same system.

There will be a PR shortly.

Thank you!

**Comment by Gonmeso** [comment]
At the `Installation` docs we have added a new entry showcasing that we recommend `pyenv` to handle python environments and stating that python 3.11 is needed! The changes have been added in #26
