### ISSUE TITLE
Add --size option to transpile command

### ISSUE THREAD

**Issue by alejandromartinezgotor** [gizatechxyz/giza-cli#50]
I'm having memory issues when trying to transpile the model generated by the tutorial https://github.com/gizatechxyz/Giza-Hub/tree/token_trend_action/awesome-giza-actions/trend_token_prediction. Currently, there is no option to change the size when executing the transpile command. The deployment command has the --size option, but the transpile command does not.

**Comment by Gonmeso** [comment]
This could be added as a `Typer` option in the transpile command under `commands/versions.py` feel free to open a PR.

**Comment by Gonmeso** [comment]
WEW the latest changes this is deprecated as transpilation instance is using bigger compute by default
